// DDDProfiler.idl : IDL source for DDDProfiler
//

// This file will be processed by the MIDL tool to
// produce the type library (DDDProfiler.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(F17D4A2B-29ED-4E36-BED3-E5040D018A4E),
	pointer_default(unique)
]
interface ICodeInjection : IUnknown{
};
[
	uuid(B8789034-F47B-4920-8D93-FFAF6A753FF5),
	version(1.0),
]
library DDDProfilerLib
{
	importlib("stdole2.tlb");
	[
		uuid(BDD57A0C-D4F7-486D-A8CA-86070DC12FA0)		
	]
	coclass CodeInjection
	{
		[default] interface ICodeInjection;
	};
};

